---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность удалять товар из корзины
  - Оформление заказа должно работать
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - При выборе языка все элементы сайта должны быть переведены на соответствующий выбранный язык
  - Валюта должна соответствовать региону пользователя
  - При оформлении заказа пользователь должен быть зарегистрирован и авторизован
  - У пользователя должны быть указаны контактные данные для оформления заказа
  - В поле цены нельзя ввести отрицательное значение
  - В поле цены можно вводить только цифры
  - Нельзя добавить в корзину товар, которого нет в наличии
  - Корзина с товарами сохраняется даже после того, как пользователь покинул страницу
  - На сайте в фильтре отображены все категории товаров, которые есть в магазине
  - На сайте в фильтре отображены все бренды товаров, которые есть в магазине
  - При обновлении страницы пользователь должен остаться на той странице, на которой перезагружал страницу
